SmartBear/smartbear-mcp

- .github/workflows/node-ci.yml
- eslint.config.js
- insight-hub/client.ts
- insight-hub/client/api/base.ts
- package-lock.json
- package.json
- reflect/client.ts
Added a GitHub workflow to ensure TS code compiles and source files pass the linting rules when code is pushed
This PR uses ESLint which is the defacto code quality tool across JS repositories, and runs on GitHub actions to avoid the requirement for additional third party tooling
Installed and configured ESLint
> Configure Node CI

- package-lock.json
- package.json
Update package name and version, for publishing to correct scope
Updated `name` and `version` in `package.json`
No code changes
> Change package name and version for publishing

- api-hub/README.md
- api-hub/client.ts
- reflect/client.ts
Fix typos in ReadMe and code
API-Hub ReadMe
Reflect client.ts
Built and testing via MCP Inspector
> chore(repo): fix minor typos

- package.json
Adds more fields to package.json so that images and links work in NPM. Also added links to the homepage and repo.
> Add more fields to package.json and fix links in npm

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
Add changelog and increment version
> Add changelog and update readme with latest

- .github/workflows/sync-main-to-next.yml
Fixes the sync to next workfow for requesting the review
Updates `.github/workflows/sync-main-to-next.yml`
Tested manually on a separate repo
> Fix requesting review method

- package-lock.json
- package.json
See [Scripts accessing packages that are not listed as dependencies](https://github.com/SmartBear/smartbear-mcp/issues/59)
> Add zod as a dependency

- api-hub/client.ts
- common/server.ts
- common/types.ts
- docs/products/SmartBear MCP Server/insight-hub-integration.md
- insight-hub/client.ts
- reflect/client.ts
- tests/unit/common/server.test.ts
- tests/unit/insight-hub/client.test.ts
To avoid the name and titles getting out of sync, I've remove the separate field and derived it all from the title.
> feat: derive tool name from title

- CHANGELOG.md
- docs/products/SmartBear MCP Server/getting-started.md
- docs/products/SmartBear MCP Server/mcp-server-capabilities.md
Release 4.0.0
Updated `CHANGELOG.md` with minor nitpicks and documentation for Portal.
> Release 4.0.0

- docs/custom-words.txt
- docs/products/SmartBear MCP Server/getting-started.md
Fixes violations discovered in https://github.com/SmartBear/smartbear-mcp/actions/runs/17259526592/job/48977738215.
Future releases should not have this issue, thanks to https://github.com/SmartBear/smartbear-mcp/pull/81
> chore: fix cspell violations

- docs/products/SmartBear MCP Server/mcp-server.md
fix a bad link within the docs
change link in markdown file
> chore(docs): fix docs link

- CHANGELOG.md
- docs/products/SmartBear MCP Server/contract-testing-with-pactflow.md
Update CHANGELOG.md and contract-testing-with-pactflow.md
> update changelog and docs for PactFlow

- CONTRIBUTING.md
Add instructions to help new contributors use our standards.
> docs: add pre-commit to contributing

- CONTRIBUTING.md
> docs: update table of contents

- CONTRIBUTING.md
Update contributing guide with new folder structure
No functional changes
> chore: update contributing guide with new folder structure

- src/bugsnag/client.ts
- src/tests/unit/bugsnag/client.test.ts
Updates the "List Project Errors" tool to use default time and error status filters if none are specified in the tool input. The default filters match the dashboard defaults:
- `event.since: 30d`
- `error.status: open`
The defaults are applied both on the input schema and when building the request options - any filters supplied in the tool input will be combined with the defaults.
Updated unit tests and tested manually
> Apply default time and status filters in list errors tool

- CHANGELOG.md
Updating changelog with pactflow changes
> chore: update changelog for pactflow

- src/api-hub/client.ts
- src/api-hub/client/api.ts
- src/api-hub/client/configuration.ts
- src/api-hub/client/index.ts
- src/api-hub/client/tools.ts
- src/api-hub/client/types.ts
- src/index.ts
- src/tests/unit/api-hub/api.test.ts
- src/tests/unit/api-hub/client.test.ts
This PR refactors the `api-hub` module to follow the established architectural patterns used in other modules (i.e., Pactflow and Bugsnag), implementing a cleaner, more maintainable modular structure.
> SWG-16141 - Refactor ApiHubClient and introduce ApiHubAPI and configuration classes for improved API interaction (SWG-16338)

- src/api-hub/client.ts
- src/api-hub/client/api.ts
- src/api-hub/client/types.ts
- src/tests/unit/api-hub/api.test.ts
- src/tests/unit/api-hub/client.test.ts
This pull request refactors the registration of tools in the `ApiHubClient` class to simplify how tool parameters are handled and to improve code clarity. It also updates the associated unit tests to match these changes and modernizes some test assertions for better safety and readability.
> refactor(ApiHubClient): SWG-16338 simplify tool registration by destructuring handler and formatResponse

- biome.jsonc
- src/pactflow/client.ts
- src/tests/unit/pactflow/client.test.ts
- src/tests/unit/pactflow/promptutils.test.ts
- src/tests/unit/pactflow/utils.test.ts
- vitest.config.ts
Improve test coverage of pactflow integration.
Before:-
After:-
> chore: improve pactflow test coverage

- .github/workflows/publish-npm.yml
- .github/workflows/publish.yaml
- server.json
Unify the publication process into a single workflow. It includes: npm, Docker (ECR), GitHub MCP registry.
> Unified publication process
